### ISSUE TITLE
Subscribing to podcast in overcast doesn't work

### ISSUE THREAD

**Issue by jeena** [jeena/jeena.net-bugtracker#21]
@ckruse has written to the developer, we'll see what happens.

**Comment by ckruse** [comment]
Did the overcast author get back to you? He didn't answer to me.

**Comment by jeena** [comment]
No, I was talking to Tim who also uses Overcast and he said everything is working for him, he subscribed manually to the rss feed and he tested searching in it (which uses the iTunes catalog, in which this podcast is now too) and subscribing, that worked too without problems.
